version: '3'
services:
  mysql:
    image: mariadb:10.4.7
    env_file: .env
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - 13306:3306
    command: |
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "--password=password"]
      timeout: 10s
      retries: 10
  login-api:
    image: openjdk:8
    env_file: .env
    volumes:
      - ./run.sh:/home/demo/run.sh
      - ./demo-login-api/build/libs:/home/demo/libs
    ports:
      - 8001:8080
    depends_on:
      - mysql
    command: bash -c "cd /home/demo && sh run.sh"
  admin-api:
    image: openjdk:8
    env_file: .env
    volumes:
      - ./run.sh:/home/demo/run.sh
      - ./demo-admin-api/build/libs:/home/demo/libs
    ports:
      - 8002:8080
    depends_on:
      - mysql
    command: bash -c "cd /home/demo && sh run.sh"
  customer-api:
    image: openjdk:8
    env_file: .env
    volumes:
      - ./run.sh:/home/demo/run.sh
      - ./demo-customer-api/build/libs:/home/demo/libs
    ports:
      - 8003:8080
    depends_on:
      - mysql
    command: bash -c "cd /home/demo && sh run.sh"
  restaurant-api:
    image: openjdk:8
    env_file: .env
    volumes:
      - ./run.sh:/home/demo/run.sh
      - ./demo-restaurant-api/build/libs:/home/demo/libs
    ports:
      - 8004:8080
    depends_on:
      - mysql
    command: bash -c "cd /home/demo && sh run.sh"
#  demo-web:
#    image: node:10.16.3
#    volumes:
#      - ./demo-web:/home/demo
#    ports:
#      - 8082:3000
#    environment:
#      - VUE_APP_API_BASE_URL=http://localhost:8002
#      - VUE_APP_LOGIN_API_BASE_URL=http://localhost:8001
#    command: bash -c "cd /home/demo && npm run serve"
#    healthcheck:
#      test: curl -sS http://localhost:8080 || exit 1
#      timeout: 10s
#      retries: 10

